#!/bin/bash
APPDIR=/opt/bojongbot/
cat iplist | while read line
do
        set -- $line
        ping -q -c2 $2 > /dev/null

        if [ $? -eq 0 ]
        then
                echo $1 "Pingable"
        else
                $APPDIR/sendtelegram -c $APPDIR/telegramrc -m "$1 Not Pingable - `date`"
        fi
done

